apiVersion: v1
kind: Service
metadata:
  name:  accountsservice-svc
  labels:
    app: accountsservice
spec:
  selector:
    app:  accountsservice
  type: NodePort
  ports:
   - port:  3001
     nodePort: 30003
     protocol: TCP