apiVersion: v1
kind: ReplicationController
metadata:
  name: accountsservice-rc
spec:
  replicas: 5
  selector:
    app: accountsservice
  template:
    metadata:
      labels:
        app: accountsservice
    spec:
      containers:
        - name: hello-ctr
          image: vinitkumargoel/lbgpoc_accountsservice:latest
          ports:
            - containerPort: 3001