apiVersion: v1
kind: ReplicationController
metadata:
  name: offeringsservice-rc
spec:
  replicas: 5
  selector:
    app: offeringsservice
  template:
    metadata:
      labels:
        app: offeringsservice
    spec:
      containers:
        - name: hello-ctr
          image: vinitkumargoel/lbgpoc_offeringsservice:latest
          ports:
            - containerPort: 3003