apiVersion: v1
kind: Service
metadata:
  name:  poc-frontend-svc
  labels:
    app: poc-frontend
spec:
  selector:
    app:  poc-frontend
  type: NodePort
  ports:
   - port:  3004
     nodePort: 30006
     protocol: TCP