apiVersion: v1
kind: Service
metadata:
  labels:
    app: poc-frontend
  name: poc-frontend-rc
  namespace: default
spec:
  ports:
  - nodePort: 32097
    port: 30004
    protocol: TCP
    targetPort: 30004
  selector:
    app: poc-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}