apiVersion: v1
kind: ReplicationController
metadata:
  name: poc-frontend-rc
spec:
  replicas: 2
  selector:
    app: poc-frontend
  template:
    metadata:
      labels:
        app: poc-frontend
    spec:
      containers:
        - name: hello-ctr
          image: vinitkumargoel/lbgpoc_new_forntend:latest
          ports:
            - containerPort: 3004